### ISSUE TITLE
Custom options for exchange

### ISSUE THREAD

**Issue by duylong** [mrtazz/statsd-amqp-backend#8]
Hi,

Add some options:
- To change the default exchange type (example: exchange_type => "direct", key routing generated internally, why not as the graphite format: "globalPrefix + prefixGauge + key")
- To disable ssl check (example: verify_ssl => "false").

**Comment by aw** [comment]
Sorry I can't change the default exchange type without breaking backwards compatibility.

As for SSL, the option is `rejectUnauthorized`.
